image: docker:cli

stages:
  - test_and_scan

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

services:
    - docker:dind

snyk:
  stage: test_and_scan
  image: node:latest
  variables:
    SNYK_TOKEN: ${SNYK_API_TOKEN}
  script:
    - npm config set cache .npm --global
    - npm install -g snyk
    - snyk auth $SNYK_TOKEN
    - cd MathSheetFrontend
    - snyk monitor --file-package.json --severity-threshold=high --pkg-manager=npm
    - snyk code test --all-projects --severity-threshold=high
    - cd .. && cd MathSheetBackend
    - snyk monitor --all-projects --severity-threshold=high --pkg-manager=npm
    - snyk code test --all-projects --severity-threshold=high
  allow_failure: false

test:
  stage: test_and_scan
  script:
    - apk update
    - apk add --no-cache python3 py3-pip
    - python3 -m venv /venv
    - source /venv/bin/activate
    - pip install pytest selenium
    - docker compose up -d
    - sleep 20
    - python test_mathsheet.py

zap_scan:
  stage: test_and_scan
  script:
     - docker ps
     - docker run -t ghcr.io/zaproxy/zaproxy:stable zap-baseline.py -t https://864d-110-159-182-228.ngrok-free.app
  artifacts:
    paths:
      - zap_report.html
    expire_in: 1 week
  allow_failure: false

trivy_scan:
  stage: test_and_scan
  script:
    - apk add --no-cache sudo
    - wget https://github.com/aquasecurity/trivy/releases/download/v0.55.0/trivy_0.55.0_Linux-64bit.tar.gz
    - tar -xzf trivy_0.55.0_Linux-64bit.tar.gz
    - chmod +x ./trivy
    - sudo mv ./trivy /usr/local/bin/
    - cd MathSheetFrontend
    - docker build -t frontendmsprod .
    - trivy --cache-dir .trivy/cache image --severity HIGH,CRITICAL --no-progress --exit-code 0 frontendmsprod
    - cd ../MathSheetBackend
    - docker build -t backendmsprod .
    - trivy --cache-dir .trivy/cache image --severity HIGH,CRITICAL --no-progress --exit-code 0 backendmsprod
  allow_failure: false