version: "3.8"

services:
  backend:
    build:
      context: ./MathSheetBackend
      dockerfile: Dockerfile
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - MathSheetNetwork

  frontend:
    build:
      context: ./MathSheetFrontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - MathSheetNetwork

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    networks:
      - MathSheetNetwork

volumes:
  postgres-volume:

networks:
  MathSheetNetwork:
    driver: bridge
